### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (18,) (36,)

### ISSUE THREAD

**Issue by florestankorp** [ocampor/notebooks#14]
I'm trying to follow along with your [Medium article](https://towardsdatascience.com/automatic-image-quality-assessment-in-python-391a6be52c11) with these [steps](https://github.com/ocampor/notebooks/blob/master/notebooks/image/quality/brisque.ipynb) and get the following error. When skipping `scale_features` the code compiles and returns a score, but it seems all over the place with bad images getting scores as high as 90!

```error
Traceback (most recent call last):
  File "image_select.py", line 183, in <module>
    calculate_image_quality_score(brisque_features)
  File "image_select.py", line 167, in calculate_image_quality_score
    scaled_brisque_features = scale_features(brisque_features)
  File "image_select.py", line 162, in scale_features
    return -1 + (2.0 / (max_ - min_) * (features - min_))
ValueError: operands could not be broadcast together with shapes (18,) (36,) 
```

**Comment by ocampor** [comment]
Sorry, you will need to be more specific for me to understand your problem.

**Comment by ocampor** [comment]
Closing because of inactivity. Please feel free to re-open if you provide more context.

**Comment by GKG1312** [comment]
Hi @ocampor , 
I am getting the same error. This is happening while scaling the features.
`scaled_brisque_features = scale_features(brisque_features)`

The issue is the features generated (named as `brisque_features`) has length of 18, however the length of `min_` and `max_` are 36, which I think we are loading through pickle file. This is causing the error.
| Feature ID      | Feature Description                            | Computation Procedure            |
|-----------------|------------------------------------------------|----------------------------------|
| $f_1-f_2$       | Shape and variance                             | Fit GGD to MSCN coefficients     |
| $f_3-f_6$       | Shape, mean, left variance, right variance     | Fit AGGD to H pairwise products  |
| $f_7-f_{10}$    | Shape, mean, left variance, right variance     | Fit AGGD to V pairwise products  |
| $f_{11}-f_{14}$ | Shape, mean, left variance, right variance     | Fit AGGD to D1 pairwise products |
| $f_{15}-f_{18}$ | Shape, mean, left variance, right variance     | Fit AGGD to D2 pairwise products |

Can you you explain this, why this is happening?
In your case you are not getting any error because of the following lines:
```
downscaled_image = cv2.resize(gray_image, None, fx=1/2, fy=1/2, interpolation = cv2.INTER_CUBIC)
downscale_brisque_features = calculate_brisque_features(downscaled_image, kernel_size=7, sigma=7/6)

brisque_features = np.concatenate((brisque_features, downscale_brisque_features))
```
This raises the question, Why it is required to downscale the image for which we want to calculate the score? Is it possible to get score directly (without concatenating downscaled version) for an image?
